DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id VARCHAR(31) NOT NULL PRIMARY KEY,
  nickname VARCHAR(127) UNIQUE,
  avatar_url VARCHAR(254) UNIQUE,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS teams;
CREATE TABLE teams (
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name VARCHAR(127) NOT NULL,
  description TEXT,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS users_teams;
CREATE TABLE users_teams (
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  user_id VARCHAR(31) NOT NULL,
  team_id BIGINT UNSIGNED NOT NULL,
  role VARCHAR(127) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE users_teams ADD CONSTRAINT fk_user_id_on_users_teams FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE users_teams ADD CONSTRAINT fk_team_id_on_users_teams FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE CASCADE;
